👨‍🔬 experimenting with pyinstaller, pyoxidizer and github actions test
REVERT ME: adding pyinstaller branch for dev testing

bump

add spec file

move files around

move

no rel

mv

paths

add requirements.txt

fix requirements.txt generation

stab in the dark

back1forward1

add pyinstaller dep

works in act

add ridiculous path

set python requires to 3.7

finally appease pyinstaller

the trick was to add a stub entrypoint for pyinstaller to use (pyinstaller_entry.py)

from: https://realpython.com/pyinstaller-python/

fix action path (works in act)

bump byproject to pyhon 37 too

attempt windows

whoops

 fix

names (woot! works for windows build)

(i wrote this in here after the fact)

almost working pyoxidizer: compiles and runs, but cmd params are weird

remvoed double adding, didn't fix it

didn't work, import error:

Traceback (most recent call last):
  File "/Users/nik/Code/personal/agora/roam2agora/./pyinstaller_entry.py", line 1, in <module>
    from src.roam2agora.main import main
ModuleNotFoundError: No module named 'src'

didn't work: click wasn't present because you didn't pipinstall

compiles, but same weirdass python cmdline options

basically, it's running as if it's python:

$ roam2agora -V
Python 3.8.6
during initializing Python core: could not format PyStatus

🎉 it worked! Also, i'm an idiot

turns out during experimenting I had uncommented python interpreter mode in pyoxide conf

🤦‍♂️

so probably the earlier working combos that were giving me python's
cmdline options were also succesful

condensed version:
```python
def make_dist():
    return default_python_distribution()
def make_exe(dist):
    policy = dist.make_python_packaging_policy()
    python_config = dist.make_python_interpreter_config()
    python_config.run_filename = CWD + "/roam2agora"
    exe = dist.to_python_executable(
        name="roam2agora",
        packaging_policy=policy,
        config=python_config,
    )
    exe.add_python_resources(exe.pip_install(["-r", CWD + "/requirements.txt"]))
    exe.add_python_resources(exe.read_package_root(
       path=CWD + "/src",
       packages=["roam2agora"],
    ))
    return exe
    ...
```